 default: &default
   adapter: mysql2
   host: "<%= ENV["SQL_HOST"] %>"
   username: "<%= ENV["SQL_USER"] %>"
   password: "<%= ENV["SQL_PASSWORD"] %>"

development:
  <<: *default
  database: sprit_development

test:
  <<: *default
  database: sprit_test

production:
  <<: *default
  database: sprit
